# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

domain: shafouz.github.io
url: https://shafouz.github.io  
baseUrl: /

title: shafouz blog
author:
  name: "shafouz"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima
minima:
  skin: dark 

social_links:
  - { social: "HackerOne", icon: "fa-solid fa-bug", user_url: "https://hackerone.com/shafou" }
  - { social: "Github", icon: "fab fa-github",  user_url: "https://github.com/shafouz" }
  - { social: "Twitter", icon: "fab fa-twitter", user_url: "https://twitter.com/shafouzzzzzz" }
  - { social: "LinkedIn", icon: "fab fa-linkedin", user_url: "https://www.linkedin.com/in/joao-luca/" }
  - { social: "Email", icon: "fa-solid fa-envelope", user_url: "mailto:jlmacedomatos@gmail.com" }

header_pages:
  - posts.markdown
  - about.markdown

google_analytics: G-F6L4J94HSJ
